// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoR8O63AYKDo1VbbmJV3i0gtbwMaIBO38',
    appId: '1:641511985723:web:c4ddc2779771210145c21e',
    messagingSenderId: '641511985723',
    projectId: 'flutter-firebase-app-2a76e',
    authDomain: 'flutter-firebase-app-2a76e.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-2a76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApO_UYxNlVfLbzYPQ_oe3cLN9PmMP6sao',
    appId: '1:641511985723:android:7459f3ddce3c8c4c45c21e',
    messagingSenderId: '641511985723',
    projectId: 'flutter-firebase-app-2a76e',
    storageBucket: 'flutter-firebase-app-2a76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUYoq-0ykhg0ebtr-mKOofLEOxpCPqB2s',
    appId: '1:641511985723:ios:7f8c2e1bfb39d2ac45c21e',
    messagingSenderId: '641511985723',
    projectId: 'flutter-firebase-app-2a76e',
    storageBucket: 'flutter-firebase-app-2a76e.appspot.com',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUYoq-0ykhg0ebtr-mKOofLEOxpCPqB2s',
    appId: '1:641511985723:ios:ed8a5f4855fe4b0745c21e',
    messagingSenderId: '641511985723',
    projectId: 'flutter-firebase-app-2a76e',
    storageBucket: 'flutter-firebase-app-2a76e.appspot.com',
    iosBundleId: 'com.example.projet.RunnerTests',
  );
}
